INSERT INTO questions (question) VALUES 
('Who is the all-time leading scorer in NBA history?'), 
('Who is the all-time leader in games played in NBA history?'), 
('Which franchise has won the most NBA championships?'), 
('Which number did Tim Duncan wear?'), 
('Kobe Bryant won 5 NBA championships. How many times did he win finals MVP?'), 
('Who is the all-time leader in blocks in NBA history?'), 
('How many NBA championships did Bill Russell win?'), 
('Where did Larry Bird attend college?'), 
('Who holds the NBA record for most career 3-point field goals?'), 
('Which of the following players was not selected #1 overall in the NBA draft?');

INSERT INTO answers (answer, question_id, is_correct) VALUES 
('Kareem Abdul-Jabbar', 1, true), 
('Michael Jordan', 1, false), 
('Wilt Chamberlain', 1, false), 
('Kobe Bryant', 1, false), 
('Robert Parish', 2, true), 
('Karl Malone', 2, false),
('Kevin Garnett', 2, false),
('Kareem Abdul-Jabbar', 2, false),
('Boston Celtics', 3, true), 
('LA Lakers', 3, false), 
('Chicago Bulls', 3, false), 
('Detroit Pistons', 3, false), 
('21', 4, true), 
('15', 4, false), 
('24', 4, false), 
('32', 4, false), 
('2', 5, true), 
('3', 5, false), 
('4', 5, false), 
('5', 5, false), 
('Hakeem Olajuwon', 6, true), 
('Dikembe Mutombo', 6, false), 
('Mark Eaton', 6, false), 
('Tim Duncan', 6, false), 
('11', 7, true), 
('6', 7, false), 
('8', 7, false), 
('12', 7, false), 
('Indiana State', 8, true), 
('Butler', 8, false), 
('Creighton', 8, false), 
('UMass', 8, false), 
('Ray Allen', 9, true), 
('Larry Bird', 9, false), 
('Reggie Miller', 9, false), 
('Steph Curry', 9, false), 
('Kevin Durant', 10, true),
('Kwame Brown', 10, false),
('Andrew Bogut', 10, false),
('Andrea Bargnani', 10, false);

SELECT q.id AS question_id, q.question, a.answer, a.is_correct FROM questions q LEFT JOIN answers a ON q.id = a.question_id;