INSERT INTO questions (question) VALUES 
('Who is the all-time leading scorer in NBA history?'), 
('Who is the all-time leader in games played in NBA history?'), 
('Which franchise has won the most NBA championships?'), 
('Which number did Tim Duncan wear?'), 
('Kobe Bryant won 5 NBA championships. How many times did he win finals MVP?'), 
('Who is the all-time leader in blocks in NBA history?'), 
('How many NBA championships did Bill Russell win?'), 
('Where did Larry Bird attend college?'), 
('Who holds the NBA record for most career 3-point field goals?'), 
('Which of the following players was not selected #1 overall in the NBA draft?'),
('Who was the only player to win an MVP Award in both the ABA and NBA?'),
('Who is the all-time leader in steals in NBA history?'),
('How many times did Larry Bird win the MVP?'),
('Which of the following players was not a member of the "Dream Team"?'),
('Who is the highest-scoring foreign-born player in NBA history?');

INSERT INTO answers (answer, question_id, is_correct) VALUES 
('Michael Jordan', 1, false), 
('Wilt Chamberlain', 1, false), 
('Kareem Abdul-Jabbar', 1, true), 
('Kobe Bryant', 1, false),  
('Karl Malone', 2, false),
('Robert Parish', 2, true),
('Kevin Garnett', 2, false),
('Kareem Abdul-Jabbar', 2, false),
('Boston Celtics', 3, true), 
('LA Lakers', 3, false), 
('Chicago Bulls', 3, false), 
('Detroit Pistons', 3, false), 
('15', 4, false), 
('21', 4, true), 
('24', 4, false), 
('32', 4, false), 
('2', 5, true), 
('3', 5, false), 
('4', 5, false), 
('5', 5, false),  
('Dikembe Mutombo', 6, false), 
('Hakeem Olajuwon', 6, true),
('Mark Eaton', 6, false), 
('Tim Duncan', 6, false),  
('6', 7, false), 
('8', 7, false), 
('12', 7, false), 
('11', 7, true),
('Butler', 8, false), 
('Creighton', 8, false), 
('UMass', 8, false), 
('Indiana State', 8, true), 
('Larry Bird', 9, false), 
('Reggie Miller', 9, false),
('Ray Allen', 9, true),  
('Steph Curry', 9, false), 
('Kevin Durant', 10, true),
('Kwame Brown', 10, false),
('Andrew Bogut', 10, false),
('Andrea Bargnani', 10, false),
('Moses Malone', 11, false),
('Julius Erving', 11, true),
('George Gervin', 11, false),
('Spencer Haywood', 11, false),
('Magic Johnson', 12, false),
('Isaiah Thomas', 12, false),
('Gary Payton', 12, false),
('John Stockton', 12, true),
('2', 13, false),
('3', 13, true),
('4', 13, false),
('5', 13, false),
('Karl Malone', 14, false),
('Scottie Pippen', 14, false),
('David Robinson', 14, false),
('Isiah Thomas', 14, true),
('Dirk Nowitzki', 15, true),
('Hakeem Olajuwon', 15, false),
('Patrick Ewing', 15, false),
('Tim Duncan', 15, false);






SELECT q.id AS question_id, q.question, a.answer, a.is_correct FROM questions q LEFT JOIN answers a ON q.id = a.question_id;